import React from 'react';
import SEO from '../../components/SEO';
import { 
  FileText, 
  ShieldCheck, 
  FileCheck, 
  HelpCircle,
  Building,
  CheckCircle,
  AlertCircle
} from 'lucide-react';

const SupportedDocuments = () => {
  const documents = [
    {
      title: 'Form 16 (Part A & B)',
      what: 'The salary tax deduction certificate containing taxable salary components, TDS declarations, and Section 80C/80D relief values.',
      who: 'Issued annually by your employer on or before June 15th of the assessment year.',
      why: 'Serves as the baseline for personal tax returns, detailing standard deductions, HRA, professional tax, and net taxable salary.',
      how: 'AI extracts employer PAN, gross salary breakdowns, HRA allowances, and TDS deductions to compare with credit reports.',
      fields: ['Employer PAN', 'Gross Salary (Section 17)', 'Sec 16 Deductions', 'TDS under Sec 192']
    },
    {
      title: 'Annual Information Statement (AIS)',
      what: 'A comprehensive summary of all financial transactions of a taxpayer, containing interest income, mutual funds, stock trades, and properties.',
      who: 'Issued by the Income Tax Department of India, accessible on the compliance portal.',
      why: 'Required to ensure you report all external incomes (like savings interest or dividends) that are not present in Form 16.',
      how: 'AI reads transaction logs, groups interest and dividend income values, and flags securities sales for capital gains.',
      fields: ['Savings Interest', 'Dividends', 'Mutual Fund transactions', 'Stock market transactions']
    },
    {
      title: 'Form 26AS',
      what: 'The consolidated tax credit statement capturing all taxes deducted at source (TDS), collected at source (TCS), and advance taxes paid.',
      who: 'Generated by the Income Tax Department through the TRACES portal.',
      why: 'Confirms that the tax deducted by your employer or banks has actually reached the government ledger.',
      how: 'AI parses quarterly TDS credits, verifies deductor PAN listings, and matches total credits against Form 16 records.',
      fields: ['TDS on Salary', 'TDS on Interest (Sec 194A)', 'Advance Tax payments', 'Self-Assessment Taxes']
    },
    {
      title: 'Income Tax Notices',
      what: 'Communications sent regarding filing defects, arithmetic adjustments, regime discrepancies, or income escape concerns.',
      who: 'Issued by the Central Processing Centre (CPC) or local assessing officers (Section 143(1), 139(9), 148, etc.).',
      why: 'Requires immediate response to avoid penalty interest rates or prosecution proceedings.',
      how: 'AI reads notice sections, explains specific clauses in simple words, identifies the target mismatch, and drafts response points.',
      fields: ['Notice Section', 'CPC Adjustment Value', 'Defect description', 'Response timeline']
    },
    {
      title: 'ITR Acknowledgment (ITR-V)',
      what: 'The verification sheet generated after filing the Income Tax Return, detailing final declared income, tax paid, and status.',
      who: 'Generated by the taxpayer and verified by CPC Bangalore.',
      why: 'Serves as standard proof of filing and is required for home loan, visa, and corporate loan approvals.',
      how: 'AI extracts total gross income, tax computations, refunds due, and e-verification timeline states.',
      fields: ['ITR Type (1, 2, 3, 4)', 'Total Taxable Income', 'Final Tax Paid', 'Verification Date']
    },
    {
      title: 'Salary Slips',
      what: 'Monthly statement detailing basic pay, dearness allowance, HRA, professional tax, EPF contributions, and variables.',
      who: 'Provided monthly by employers to employee staff.',
      why: 'Helps track monthly HRA allocations, variable structures, and updates to standard allowances.',
      how: 'AI parses monthly basic salary, EPF employee portions, rent allowance lines, and lists Section 80C PF deductions.',
      fields: ['Basic Salary', 'House Rent Allowance', 'Provident Fund (EPF)', 'Professional Tax']
    },
    {
      title: 'Investment Proofs',
      what: 'Receipts and statements representing LIC policies, PPF slips, medical insurance, home loan certificates, and school fees.',
      who: 'Issued by insurance companies, banks, schools, and landlords.',
      why: 'Required to substantiate Chapter VI-A deductions claimed in your final return or to your employer.',
      how: 'AI validates transaction date, receipt sums, policyholders, and maps values to Section 80C or Section 80D categories.',
      fields: ['LIC Premium Receipt', 'ELSS Mutual Fund Statement', 'Medical Premium receipt', 'House Rent Receipts']
    }
  ];

  return (
    <>
      <SEO 
        title="Supported Documents - Form 16, AIS, 26AS, & Notices" 
        description="Learn which tax forms are supported by TaxReview AI. Discover what Form 16, AIS, Form 26AS, salary slips, and tax notices are, and how AI parses them."
      />

      {/* Header section */}
      <section className="relative py-16 md:py-24 border-b border-slate-200/50 dark:border-slate-900/50 overflow-hidden">
        <div className="absolute top-[10%] left-1/3 -z-10 h-[450px] w-[450px] rounded-full bg-primary-500/5 blur-[140px]" />
        
        <div className="mx-auto max-w-5xl px-4 md:px-8 text-center space-y-6">
          <h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl md:text-5xl">
            Supported Indian Tax Documents
          </h1>
          <p className="text-base md:text-lg text-slate-500 dark:text-slate-400 max-w-xl mx-auto leading-relaxed">
            See how our AI auditing pipeline reads, parses, and extracts structural fields from various tax forms.
          </p>
        </div>
      </section>

      {/* Documents Grid */}
      <section className="py-16 md:py-24">
        <div className="mx-auto max-w-7xl px-4 md:px-8">
          <div className="space-y-12">
            {documents.map((doc, idx) => (
              <div 
                key={idx} 
                className="border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 rounded-3xl p-6 md:p-8 shadow-sm grid grid-cols-1 lg:grid-cols-3 gap-8 hover:shadow-md transition-shadow duration-300"
              >
                
                {/* General Info Column */}
                <div className="lg:col-span-1 space-y-4">
                  <div className="flex items-center space-x-3">
                    <div className="rounded-xl bg-primary-500/10 text-primary-600 dark:text-primary-400 p-2.5">
                      <FileText className="h-5.5 w-5.5" />
                    </div>
                    <h2 className="text-lg font-bold text-slate-900 dark:text-white">{doc.title}</h2>
                  </div>
                  
                  <div className="space-y-1.5">
                    <span className="text-[10px] font-extrabold text-primary-600 dark:text-primary-400 uppercase tracking-widest block">What It Is</span>
                    <p className="text-xs md:text-[13px] text-slate-600 dark:text-slate-300 leading-relaxed font-medium">{doc.what}</p>
                  </div>

                  <div className="space-y-1.5">
                    <span className="text-[10px] font-extrabold text-primary-600 dark:text-primary-400 uppercase tracking-widest block flex items-center gap-1.5">
                      <Building className="h-3.5 w-3.5" />
                      <span>Who Issues It</span>
                    </span>
                    <p className="text-xs md:text-[13px] text-slate-600 dark:text-slate-300 leading-relaxed font-semibold">{doc.who}</p>
                  </div>
                </div>

                {/* Importance and AI Parsing Column */}
                <div className="lg:col-span-1 space-y-5">
                  <div className="space-y-1.5">
                    <span className="text-[10px] font-extrabold text-primary-600 dark:text-primary-400 uppercase tracking-widest block">Why It Matters</span>
                    <p className="text-xs md:text-[13px] text-slate-600 dark:text-slate-300 leading-relaxed font-medium">{doc.why}</p>
                  </div>

                  <div className="space-y-1.5">
                    <span className="text-[10px] font-extrabold text-primary-600 dark:text-primary-400 uppercase tracking-widest block">How AI Reviews It</span>
                    <p className="text-xs md:text-[13px] text-slate-700 dark:text-slate-200 leading-relaxed font-bold bg-slate-50 dark:bg-slate-950/40 p-3 rounded-xl border border-slate-100 dark:border-slate-850/60">{doc.how}</p>
                  </div>
                </div>

                {/* Field Extraction Column */}
                <div className="lg:col-span-1 bg-slate-50 dark:bg-slate-950 p-5 rounded-2xl border border-slate-100 dark:border-slate-850 flex flex-col justify-between">
                  <div className="space-y-3">
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block flex items-center gap-1">
                      <FileCheck className="h-4 w-4 text-green-500" />
                      <span>Extracted Fields</span>
                    </span>
                    <div className="grid grid-cols-2 gap-2">
                      {doc.fields.map((field, fIdx) => (
                        <div key={fIdx} className="bg-white dark:bg-slate-900 border border-slate-200/60 dark:border-slate-800 rounded-lg p-2 text-[10px] text-slate-600 dark:text-slate-300 font-semibold truncate">
                          {field}
                        </div>
                      ))}
                    </div>
                  </div>
                  <div className="mt-4 text-[9px] text-slate-400 flex items-center gap-1.5">
                    <ShieldCheck className="h-4 w-4 text-green-500" />
                    <span>Layout integrity checked for OCR alignment</span>
                  </div>
                </div>

              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
};

export default SupportedDocuments;
