import React from 'react';
import SEO from '../../components/SEO';

const Terms = () => {
  return (
    <>
      <SEO 
        title="Terms & Conditions - Service Agreements" 
        description="Review the TaxReview AI Terms of Service. Understand usage guidelines, software limitations, and taxpayer audit liability terms."
      />

      <section className="py-16 md:py-24 max-w-[800px] mx-auto px-4 md:px-8 space-y-6">
        <h1 className="text-3xl font-extrabold text-slate-900 dark:text-white border-b border-slate-100 dark:border-slate-850 pb-4">
          Terms & Conditions
        </h1>
        <p className="text-xs text-slate-400">Last updated: July 15, 2026</p>

        <div className="text-sm md:text-[17px] text-slate-600 dark:text-slate-300 space-y-6 leading-[1.8] text-justify hyphens-auto">
          <p>
            By accessing or using the TaxReview AI platform, you agree to comply with and be bound by the following Terms and Conditions of service.
          </p>

          <h2 className="text-sm font-bold text-slate-900 dark:text-white uppercase tracking-wider pt-4 text-left">1. Scope of Service</h2>
          <p>
            TaxReview AI provides automated layout OCR parsing and Gemini AI auditing recommendations for Indian Income Tax documents. The platform is designed to identify potential mismatches and missing deduction allowances to assist filing preparation.
          </p>

          <h2 className="text-sm font-bold text-slate-900 dark:text-white uppercase tracking-wider pt-4 text-left">2. Liability Disclaimers</h2>
          <p>
            The reviews, recommendations, and risk reports generated by the software are for educational and preparation assistance purposes only. They do not constitute professional chartered accountancy advice. The final responsibility for correct tax return submission and payment remains solely with the individual taxpayer. TaxReview AI is not liable for e-filing penalties or notice demands.
          </p>

          <h2 className="text-sm font-bold text-slate-900 dark:text-white uppercase tracking-wider pt-4 text-left">3. Prohibited Usage</h2>
          <p>
            You agree not to upload fraudulent documents, compromised files, or malicious scripts. We reserve the right to suspend accounts that engage in service scraping or attempt infrastructure security breaches.
          </p>

          <h2 className="text-sm font-bold text-slate-900 dark:text-white uppercase tracking-wider pt-4 text-left">4. Revisions & Support</h2>
          <p>
            We regularly update our audit rules to align with yearly budget changes. For general license questions or corporate support requests, contact us at support@taxreviewai.com.
          </p>
        </div>
      </section>
    </>
  );
};

export default Terms;
